name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  cdp-workflows:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - name: Check Dockerfile Builds
        uses: docker/build-push-action@v7.1.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: trade-imports-frontend-tests:latest
#      - name: Check with Trivy
#        run: |
#          docker run -v /var/run/docker.sock:/var/run/docker.sock \
#            -v $PWD:/work \
#            aquasec/trivy:0.69.3 image \
#            --ignorefile /work/.trivyignore \
#            --ignore-unfixed \
#            --exit-code 1 \
#            trade-imports-frontend-tests:latest

# Uncomment this to run the tests in your test suite
#  tests:
#    name: Run Journey Tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: DEFRA/cdp-node-journey-test-suite-template/run-journey-tests@main
